### ISSUE TITLE
How to generate .xyt

### ISSUE THREAD

**Issue by shuaichen007** [abb-iss/distributed-fuzzy-vault#1]
Hi,

I am a freshman trying to run your code.
Would you please tell me how to generate .xyt file based on the fingerprint database?

Thanks!

**Comment by rakshi00** [comment]
Hi,

You can generate .xyt files from pictures with the MINDTCT minutiae detector from NBIS. You can find further documentation here: https://nvlpubs.nist.gov/nistpubs/Legacy/IR/nistir7392.pdf

For installing NBIS, you can also refer to the README file in this repository.
